name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Cache VS Code test downloads
        uses: actions/cache@v4
        with:
          path: .vscode-test
          key: ${{ runner.os }}-vscode-test-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-vscode-test-

      - name: Install dependencies
        run: npm ci

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test

      - name: Run tests (macOS/Windows)
        if: runner.os != 'Linux'
        run: npm test

